# This GitHub workflow deploys Bundle assets (ML asset config and more)
# defined under databricks_mlops_stacks/assets/*
# and databricks_mlops_stacks/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for databricks_data_ops Prod

on:
  push:
    branches:
      - 'main'
    paths:
      - 'data-ops/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./data-ops/

env:
  DATABRICKS_TOKEN: ${{ secrets.PROD_WORKSPACE_TOKEN }}

jobs:
  prod:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.211.0
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t prod
